kind: pipeline
type: docker
name: ci

clone:
    depth: 50

steps:
    - name: build
      image: d.ctdn.net/node
      commands:
          - yarn config set registry https://r.ctdn.net
          - yarn
          - yarn build
