kind: pipeline
type: docker
name: ci

clone:
    depth: 50

steps:
    - name: build
      image: d.ctdn.net/node
      commands:
          - npm config set registry https://r.ctdn.net
          - npm install
          - npm run build
